routes/web.php
<?php




use Illuminate\Support\Facades\Route;
use phpDocumentor\Reflection\Types\Resource_;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//----------------------------------------------------------------------------------------------------
// Otras
//----------------------------------------------------------------------------------------------------

Auth::routes();

Route::get('/', 'HomeController@index2');


//----------------------------------------------------------------------------------------------------
// Student
//----------------------------------------------------------------------------------------------------

Route::get('/estudiante', function () {
    return view('student.Dashboard');
})->middleware('Mid_Student');;

//----------------------------------------------------------------------------------------------------
// Administrator
//----------------------------------------------------------------------------------------------------



Route::get('/home', 'HomeController@index')->name('home')->middleware('Redirects');

//----------------------------------------------------------------------------------------------------
// Faculty
//----------------------------------------------------------------------------------------------------

Route::resource('user', 'UserController');
Route::resource('administrador', 'AuthorController')->middleware('Mid_Administrator');;

Route::get('facultades','FacultyController@index')->name('facultades')->middleware('Mid_Administrator');;
Route::post('facultades/create','FacultyController@create')->name('faculties.create')->middleware('Mid_Administrator');;
Route::post('facultades/store','FacultyController@store')->name('facultades.store');
Route::post('facultades/delete/{Faculty}','FacultyController@delete')->name('facultades.delete')->middleware('Mid_Administrator');;
Route::get('facultades/edit/{Faculty}','FacultyController@edit')->name('facultades.edit')->middleware('Mid_Administrator');;
Route::put('facultades/update','FacultyController@update')->name('facultades.update')->middleware('Mid_Administrator');;

//----------------------------------------------------------------------------------------------------
// Programs
//----------------------------------------------------------------------------------------------------

Route::get('Programas','ProgramController@index')->name('programs')->middleware('Mid_Administrator');;
Route::get('programas/crear','ProgramController@create')->name('programs.create')->middleware('Mid_Administrator');;
Route::post('programas/store', 'ProgramController@store')->name('programs.store')->middleware('Mid_Administrator');;
Route::delete('programas/delete/{Program}', 'ProgramController@delete')->name('programs.delete')->middleware('Mid_Administrator');;
Route::get('programas/edit/{program}', 'ProgramController@edit')->name('programs.edit')->middleware('Mid_Administrator');;
Route::put('programas/update','ProgramController@update')->name('programs.update')->middleware('Mid_Administrator');;

//----------------------------------------------------------------------------------------------------
// Campus
//----------------------------------------------------------------------------------------------------

Route::get('campus','CampusController@index')->name('campus')->middleware('Mid_Administrator');;
Route::get('campus/crear','CampusController@create')->name('campus.create')->middleware('Mid_Administrator');;
Route::post('campus/store','CampusController@store')->name('campus.store')->middleware('Mid_Administrator');;
Route::delete('campus/delete/{campus}','CampusController@delete')->name('campus.delete')->middleware('Mid_Administrator');;
Route::get('campus/edit/{campus}', 'CampusController@edit')->name('campus.edit')->middleware('Mid_Administrator');;
Route::put('campus/update', 'CampusController@update')->name('campus.update')->middleware('Mid_Administrator');;

resources/views/student/Dashboard.blade.php
@extends('layouts.app')

<div class="container">

    <form action="{{ route('logout') }}" method="post">
        @csrf
        <button type="submit">logout</button>
    </form>

</div>

<h1>EStudiante</h1>

resources/views/student/Edit.blade.php
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
    <form class="user" action="{{ route('user.update',$user->identification_card) }}" method="post" >
    @method('PUT')
    @csrf
        <table class="table table-dark">

        <thead>
          <tr>
           <th> Datos</th>
           
            <th> Edicion</th>
          
            
            
          </tr>
        </thead>
       
        <tbody>
       
           
          <tr>
            <th scope="col">nombre </th>
            <td>
            
                <div class="form-group row">
                    <input  value="{{$user->name }}"  id= "name" name="name" class="form-control" >
                    </div>
            </td>
            
          </tr>
         
          <tr>
           
            <th scope="col">direccion</th>
         
           
            <td>
                <div class="form-group row">
                    <input  value="{{$user->direction }}"  id= "direction" name="direction" class="form-control" >
                    </div>
            
            </td>
        
          </tr>
          <tr>
          
            <th scope="col">email</th>
            
         
            <td>
              
                <div class="form-group row">
                <input  value="{{$user->email}}"  id= "email" name="email" class="form-control" >
                </div>
            
            </td>
            
        
          </tr>

          <tr>
      

            <th scope="col">telefono </th>
           
            <td>
                
                <div class="form-group row">
                    <input  value="{{$user->telphone}} "  id= "telphone" name="telphone" class="form-control" >
                </div>

            </td>
            
        
          </tr>

          <tr>

           
            <th scope="col">ciudad_de_redecidencia</th>
       
    
            <td>
            
                <div class="form-group row">
                    <input  value="{{$user->city_​​of_residence}}"  id= "telphone" name="telphone" class="form-control" >
                </div>
            
            </td>
            
        
          </tr>

          <tr>

            <th scope="col">ciudad_de_origen</th>
           
           
            <td>
            
                <div class="form-group row">
                    <input  value="{{$user->city_​​of_origin}}"  id= "city_​​of_origin" name="city_​​of_origin" class="form-control" >
                </div>
            
            </td>
            
        
          </tr>

          
          <tr>

         
            <th scope="col">nacionalidad</th>
          
            <td>

            <div class="form-group row">
                <input  value="{{$user->nationality}}"  id= "city_​​of_origin" name="city_​​of_origin" class="form-control" >
            </div>

        </td>
          </tr>


          <tr>
            
            <th scope="col">facultad</th>
          
            <td>{{$user->faculty}}</td>
          </tr>


          <tr>
          
            <td>

                <button type="submit" class="btn btn-dark btn-user btn-block">
                  Editar
               </button>
            
            
            </td>
          </tr>



        </tbody>
      </table>


    </form> 

      

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

resources/views/student/charts.blade.php
<html>
  <head>
   
    <script type="text/javascript">
        const dfeg1 = {!! json_encode($consulta) !!};



             var productos = [];
            var valores = [];
           
            for (let index = 0; index < dfeg1.length; index++){
        productos.push(dfeg1[index].name_program);
        valores.push(dfeg1[index].cantidad);
    }

    </script>

    <!--Load the AJAX API-->
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">

      // Load the Visualization API and the corechart package.
      google.charts.load('current', {'packages':['corechart']});

      // Set a callback to run when the Google Visualization API is loaded.
      google.charts.setOnLoadCallback(drawChart);

      // Callback that creates and populates a data table,
      // instantiates the pie chart, passes in the data and
      // draws it.
      function drawChart() {

        // Create the data table.
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Topping');
        data.addColumn('number', 'Slices');
        for(i = 0; i < productos.length; i++)
        data.addRow([ productos[i], valores[i]]);
    

        // Set chart options
        var options = {'title':'How Much Pizza I Ate Last Night',
                       'width':400,
                       'height':300};

        // Instantiate and draw our chart, passing in some options.
        var chart = new google.visualization.PieChart(document.getElementById('chart_div'));
        chart.draw(data, options);
      }
    </script>
  </head>

  <body>
    <!--Div that will hold the pie chart-->
    <div id="chart_div"></div>
  </body>
</html>